
CREATE USER dbt_user WITH PASSWORD '***';

GRANT CONNECT ON DATABASE supermarketsales TO dbt_user;

GRANT USAGE ON SCHEMA dbt TO dbt_user;
GRANT USAGE ON SCHEMA nds TO dbt_user;
GRANT CREATE ON SCHEMA dbt TO dbt_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbt TO dbt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbt GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbt_user;

GRANT CREATE ON SCHEMA nds TO dbt_user;
GRANT SELECT ON ALL TABLES IN SCHEMA nds TO dbt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA nds GRANT SELECT ON TABLES TO dbt_user;

GRANT CREATE ON SCHEMA stage TO dbt_user;
GRANT SELECT ON ALL TABLES IN SCHEMA stage TO dbt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA stage GRANT SELECT ON TABLES TO dbt_user;

GRANT CREATE ON SCHEMA dq TO dbt_user;
GRANT SELECT ON ALL TABLES IN SCHEMA dq TO dbt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA dq GRANT SELECT ON TABLES TO dbt_user;

GRANT CREATE ON SCHEMA metadata TO dbt_user;
GRANT SELECT ON ALL TABLES IN SCHEMA metadata TO dbt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata GRANT SELECT ON TABLES TO dbt_user;

SELECT * 
FROM information_schema.role_table_grants 
WHERE grantee = 'dbt_user';



